# Generated by Django 5.0.2 on 2024-02-22 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=30)),
                ("contacts", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("comment", models.CharField(max_length=150, null=True)),
                ("cp_numb", models.CharField(max_length=20, null=True)),
                ("creation_date", models.DateField()),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
